displayName=Haggle Helper
author=gavin-lb
support=https://github.com/gavin-lb/haggle-helper
description=Helps you haggle with NPC shops to maximize your profit. Track your item costs, visualize profitable quantities and total profit, prevent unprofitable sales, see your total profit and profit/hr, and more!
tags=shop,shops,store,stores,sell,selling,buy,buying,price,prices,profit,gp,money,moneymaking,haggle,trading,overlay,tooltips,npc,npc shop,npc store,vendor
version=1.0.6
plugins=com.hagglehelper.HaggleHelperPlugin
build=standard