displayName=Haggle Helper
author=gavin-lb
support=https://github.com/gavin-lb/haggle-helper
description=Helps you buy from and sell to NPC shops
tags=shop,shops,store,stores,sell,selling,buy,buying,price,prices,profit,gp,money,moneymaking,haggle,trading,overlay,tooltips,npc,npc shop,npc store,vendor,shopscape
version=1.1.2
plugins=com.hagglehelper.HaggleHelperPlugin
build=standard